ERROR_INVALID_THANK_ID = 1
ERROR_LOGIN_REQUIRED = 2
ERROR_INVALID_LANGUAGE = 3

ERROR_MESSAGES = {
  ERROR_INVALID_THANK_ID: _('Invalid thank_id'),
  ERROR_LOGIN_REQUIRED: _('Login required'),
  ERROR_INVALID_LANGUAGE: _('Invalid language'),
  }

